### ISSUE TITLE
Forum e.l.

### ISSUE THREAD

**Issue by simendsjo** [hioa-cs/cpp_v2015#1]
Er det satt opp forum/mailing list/newsgroup/irc-kanal/gitter(https://gitter.im) e.l. for kurset?

**Comment by kybeg** [comment]
Hei!

Nei, vi har dessverre ikke noe slikt for kurset. Vi har prøvd å bruke fasilitetene i fronter så mye som mulig.

**Comment by simendsjo** [comment]
Det ligger ikke noe forum i Fronterrommet. Forumet i fronter er tilnærmet ubrukelig dessverre, men uansett bedre enn ingen ting. Skrur du det på?

**Comment by alfred-bratterud** [comment]
Jeg har brukt forum tidligere, men er redd det kan bli litt vel mye hjelp å få der ifbm. obliger. Tror vi bruker  denne issue-trackeren inntil videre!
