### ISSUE TITLE
Løsning på feilmelding ved kjøring av Alfreds script: install_from_source.sh 

### ISSUE THREAD

**Issue by henrikfischer** [hioa-cs/cpp_v2015#11]
Det kommer opp et par feilmeldinger hvis du prøver å kjøre Alfred sitt script for å installere fltk i VM'en.
Løsningen på dette er å kjøre $ sudo apt-get install libx11-dev
Feilmeldingene vil typisk se slik ut:
![11075246_10155387476070093_638788067_n](https://cloud.githubusercontent.com/assets/5310729/6690655/26dab3c6-ccc2-11e4-91d5-8b9a2c0ef359.jpg)

**Comment by alfred-bratterud** [comment]
Glimrende - jeg legger det inn i scriptet.
