### ISSUE TITLE
Ingen demo filer for f7?

### ISSUE THREAD

**Issue by gretar80** [hioa-cs/cpp_v2015#18]
Kan ikke finne flg. filer som er snakket om i forelesningsnotater f7 (polymorfi, copy, move, etc):
- copy_move.cpp
- polymorfi1.cpp 
- abstrakte_klasser.cpp
- abstrakt_interface.cpp 
- class_fileFormatValidator.h 

Er disse ikke del av pensum for prøven i morgen (14.april)?

**Comment by alfred-bratterud** [comment]
Hei, jeg skal gå igjennom dette nå for å se hva som burde vært lagt ut. Det ville være urimelig å legge ut nytt stoff nå, så det gjør jeg ikke, men hvis jeg ser at det er ting jeg har glemt å legge ut, som faktisk er gjennomgått i forelesninger "på norsk", vil det fremdeles være pensum - bare at kodeeksempler fra meg mangler. I så fall kan jeg legge det ut for å gjøre ting lettere for folk å finne eksempler, men nettkildene [cplusplus.com](http://www.cplusplus.com/) og [cppreference.com](http://en.cppreference.com/w/cpp) har eksempler på det aller meste allerede.

**Comment by alfred-bratterud** [comment]
* `copy_move.cpp` - jeg har et eksempel her, men det er komplisert, fordi målet var å "tvinge" kompilatoren til å bruke en move-constructor. Jeg tror det er like greit at jeg heller legger ut dette senere, for spesielt interesserte - bruk heller eksemplene som er linket til i forelesningsnotatene. 
* `polymorfi1.cpp` og  `abstrakte_klasser.cpp`: begge disse vises i sin helhet inne i forelesningsnotatene. Jeg kan legge dem ut for enkelhets skyld.
* `abstrakt_interface.cpp` og `class_fileFormatValidator.h` - disse kan også leses i sin helhet i notatene. Dette med abstrakt interface er ikke så veldig sentralt, så lenge man "skjønner greia". Bruk heller tid på det andre.
